### ISSUE TITLE
Usage example fails

### ISSUE THREAD

**Issue by slowkow** [0x00A/ldb#41]
Hi, I'm following the usage example shown [here](https://github.com/hij1nx/ldb/blob/master/man/ldb.1.md).

Here is my result:

``` bash
ldb ./db --put foo --value bar
In excecutable 'ldb':
Unrecognized flag/option './db'
```

Could you provide any tips? I'm interested to write a simple bash script to populate the database, but this is stopping me.

---

On the other hand, this command actually works:

``` bash
ldb -i ./db -c
```

Then, I'm able to successfully do:

```
> put foo;bar
>
> get foo
bar
```

**Comment by hij1nx** [comment]
Hmm.. works for me (haha) are you sure you've pulled the latest?
```
~/w/g/h/ldb (master) $ ldb ./testdb --put foo --value bar
~/w/g/h/ldb (master) $ ldb ./testdb --get foo
bar
```

**Comment by slowkow** [comment]
I deleted my ldb folder, pulled the latest, and tried again. Still, the same result. I'm not sure what's wrong.

I get the same behavior on a Linux server and also on a Macbook. Maybe something to do with argument parsing might to be wrong? I don't know.

```
uname -srm
Linux 2.6.18-274.el5 x86_64

uname -srmpi
Darwin 13.4.0 x86_64 i386 MacBookPro11,2
```

**Comment by 0x00A** [comment]
Seems fixed in recent versions. Closing since this is old. If this is still an issue for you please feel free to re-open.
