### ISSUE TITLE
gzip format issues - "ldb-0.0.2.tar.gz: not in gzip format"

### ISSUE THREAD

**Issue by SaiSujithReddy** [0x00A/ldb#47]
Machine:- Ubuntu
State:- clib installed successfully.  
           command "clib -v" shows 1.5.0
When running command "clib install hij1nx/ldb" It says 
       fetch : hij1nx/ldb:package.json
       gzip: ldb-0.0.2.tar.gz: not in gzip format
        tar: This does not look like a tar archive
        tar: Exiting with failure status due to previous errors

Is it due to "ldb-0.0.2.tar.gz" is not a compressed file ?

**Comment by daniellejukes** [comment]
Was this issue ever solved?

**Comment by SaiSujithReddy** [comment]
It is too late. I think i figured workaround.

**Comment by 0x00A** [comment]
That's odd because that file is produced by github when a release is made.

**Comment by daniellejukes** [comment]
Did an update and seemed to work - think I hadn't installed something properly. Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
