### ISSUE TITLE
Build failed on Ubuntu 14.04

### ISSUE THREAD

**Issue by xuanzhaopeng** [0x00A/ldb#48]
Just build as mentioned in Readme. 

g++ -o ldb ldb.cc ./lib/_.cc -I./deps/leveldb/include -std=gnu++11 -lpthread -L/usr/local/include ./deps/leveldb/out-static/libleveldb.a linenoise.o
./deps/leveldb/out-static/libleveldb.a(table_builder.o): In function `leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder_, leveldb::BlockHandle_)':
table_builder.cc:(.text+0x92f): undefined reference to `snappy::MaxCompressedLength(unsigned long)'
table_builder.cc:(.text+0x96d): undefined reference to`snappy::RawCompress(char const_, unsigned long, char_, unsigned long_)'
./deps/leveldb/out-static/libleveldb.a(format.o): In function `leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*)':
format.cc:(.text+0x4d9): undefined reference to`snappy::GetUncompressedLength(char const_, unsigned long, unsigned long_)'
format.cc:(.text+0x5ae): undefined reference to `snappy::RawUncompress(char const_, unsigned long, char_)'
collect2: error: ld returned 1 exit status
make: **\* [ldb] Error 1

**Comment by hermanjunge** [comment]
+1

**Comment by harmeetsingh0013** [comment]
Same issue for me on Ubuntu 16.04.

**What is the alternate for using ldb?**

**Comment by feifei435** [comment]
I successfully compiled on Ubuntu 14.04 with the following steps:
`
sudo apt-get autoremove libsnappy-dev
cd ./deps/leveldb
make clean && make
cd ../../
make
`
the error will disapear.Infact there's no need to install libsnappy-dev on Ubuntu14.04 to compile ldb.

**Comment by franksunjin** [comment]
I tried osx/ubuntu/rhel/centos, nothing works, also clib

**Comment by 0x00A** [comment]
osx works fine for me, but i'm getting an error with linenoise, looking into it.

**Comment by 0x00A** [comment]
@franksunjin would you mind posting the errors you are getting?

**Comment by franksunjin** [comment]
Mac:ldb$ git diff
diff --git a/Makefile b/Makefile
index f506b17..46f7150 100644
--- a/Makefile
+++ b/Makefile
@@ -34,7 +34,7 @@ deps/snappy:
        git clone --depth 1 git://github.com/0x00A/snappy.git ./deps/snappy
 
 deps/docopt:
-       git clone --depth 1 git@github.com:docopt/docopt.cpp.git ./deps/docopt
+       git clone --depth 1 https://github.com/docopt/docopt.cpp.git ./deps/docopt

Also it failed to download and build snappy somehow, I need to manually link snappy from my local

**Comment by franksunjin** [comment]
I think the issue of xuanzhaopeng@ is make failed to link snappy

**Comment by 0x00A** [comment]
@franksunjin can you post the output of the errors though? That looks like the diff of my last fix for the issue where cloning required authentication.

**Comment by gumb0** [comment]
@0x00A Here's what I'm getting on Ubuntu 14.04: https://gist.github.com/gumb0/f6651a3c1872ea9c5bbf31523b18fb47

Also installing with clib gives:
```
$ clib install hij1nx/ldb
       fetch : hij1nx/ldb:package.json

gzip: ldb-2.0.0.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

**Comment by mhirsch** [comment]
I get the same error on Fedora 24:

```
$ make
make -C ./deps/leveldb
make[1]: Entering directory '/home/mhirsch/ldb/deps/leveldb'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/mhirsch/ldb/deps/leveldb'
g++ -o ldb ldb.cc ./lib/*.cc ./deps/docopt/docopt.cpp -I./deps/leveldb/include -std=gnu++11 -lpthread -L/usr/local/include ./deps/leveldb/out-static/libleveldb.a linenoise.o
./deps/leveldb/out-static/libleveldb.a(table_builder.o): In function `leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*)':
table_builder.cc:(.text+0x730): undefined reference to `snappy::MaxCompressedLength(unsigned long)'
table_builder.cc:(.text+0x75d): undefined reference to `snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)'
./deps/leveldb/out-static/libleveldb.a(format.o): In function `leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*)':
format.cc:(.text+0x4c2): undefined reference to `snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)'
format.cc:(.text+0x570): undefined reference to `snappy::RawUncompress(char const*, unsigned long, char*)'
collect2: error: ld returned 1 exit status
Makefile:31: recipe for target 'ldb' failed
make: *** [ldb] Error 1
```
```
$ rpm -ql snappy-devel
/usr/include/snappy-c.h
/usr/include/snappy-sinksource.h
/usr/include/snappy-stubs-public.h
/usr/include/snappy.h
/usr/lib64/libsnappy.so
/usr/share/doc/snappy-devel
/usr/share/doc/snappy-devel/format_description.txt
/usr/share/doc/snappy-devel/framing_format.txt
```

**Comment by mhirsch** [comment]
FYI There's nowhere in the Makefile that adds `-lsnappy`. I just hacked it onto the end of the line 31, and it works. Probably should be added to the `DEPS` variable or something?

**Comment by liyongming1982** [comment]
I just move "-lsnappy" to the last and it works in ubuntu:
$(BIN): $(DEPS) $(LIBPATH)/*.cc deps/docopt
	$(CXX) -o $(BIN) $(SRC) $(CXXFLAGS) -lpthread -L/usr/local/lib  $(LIBLEVELDB) $(DEPS) -lsnappy
