### ISSUE TITLE
Build failed on current version OSX 

### ISSUE THREAD

**Issue by davidwowa** [0x00A/ldb#56]
Brew part is ok:
**1.** `brew install snappy`  
Result:
`==> Pouring snappy-1.1.7_1.high_sierra.bottle.tar.gz`

**2.** git Part is ok  

**3.** `make install -C ldb` its NOT ok  
Result:
`make -C ./deps/leveldb`
`make[1]: *** No targets specified and no makefile found.  Stop.`  
`make: *** [leveldb] Error 2`
Unfortunately I am not a make-scripts expert :-(.
Thx

**Comment by gillesdemey** [comment]
It seems this is not limited to OSX, but rather the Makefile for LevelDB was removed from the master branch recently.

https://github.com/google/leveldb/commit/8e75db8623703cdc25ec3cd06f82129296672489

**Comment by 0x00A** [comment]
Yep I have branch `v2.3.0` which will move everything to `cmake`.
